### ISSUE TITLE
promise-based rendering. sometimes hangs

### ISSUE THREAD

**Issue by indeyets** [FormidableLabs/rapscallion#103]
I use promise based rendering in a project. Server is build using webpack

Sometimes, while in development mode, I see that rapscallion's promise just never returns. It usually happens when code was just recently build and nodemon started the process. Killing server and starting it manually (without auto-rebuild) usually solves the issue.

I didn't notice this behavior before the update of rapscallion. I see it all the time in my dev-cycle right now (Production env works just fine, but it runs on pre-built code).

I'll add details when I have them

**Comment by indeyets** [comment]
@fleg any ideas what could cause this? error handling maybe?

**Comment by indeyets** [comment]
ok, it actually returns, but it takes several minutes. The server is in a blocked state during this period.

Second and further requests work just fine

**Comment by indeyets** [comment]
figured out the trigger. it's `NODE_ENV=development`. it works fine with other values

**Comment by ethersage** [comment]
This is new in `>= 2.1.8`?

**Comment by indeyets** [comment]
Yup. I didn't see it happening before. Might be coincidence of course. I will recheck with older version  later today

**Comment by ethersage** [comment]
I think it's possible #106 would manifest this way for promises.

**Comment by liviuignat** [comment]
Hi guys,
Maybe it's related, but the bellow code give this warning: 

```
(node:25231) Warning: a promise was created in a handler at node_modules/rapscallion/lib/consumers/node-stream.js:42:9 but was not returned from it, see http://goo.gl/rRqMUw

[1]  at Function.Promise.cast (/node_modules/rapscallion/node_modules/bluebird/js/release/promise.js:196:13)
```

code: 

```
export async function getMainComponentStream(MainComponent: any): any {
  const componentRenderer = await render(MainComponent);
  const templateRenderer = await template`<!doctype html>${componentRenderer}`;
  const componentStream = await templateRenderer.toStream();
  return componentStream;
}
```

Any ideas?

**Comment by ethersage** [comment]
@indeyets Is this fixed in `2.1.13` by chance?

**Comment by indeyets** [comment]
@ethersage it isn't. still happens here
