### ISSUE TITLE
stream chunk error

### ISSUE THREAD

**Issue by pwmckenna** [FormidableLabs/rapscallion#67]
```js
            <script dangerouslySetInnerHTML={{__html:[] }} type="text/javascript" />
```
This code (which is borderline invalid, but doesn't cause problems with renderToString), triggers the following:

```js
     Uncaught TypeError: Invalid non-string/buffer chunk
      at chunkInvalid (_stream_readable.js:393:10)
      at readableAddChunk (_stream_readable.js:148:12)
      at Readable.push (_stream_readable.js:134:10)
      at pullBatch (node_modules/rapscallion/lib/consumers/common.js:30:14)
      at Readable.read [as _read] (node_modules/rapscallion/lib/consumers/node-stream.js:32:18)
      at Readable.read (_stream_readable.js:348:10)
      at resume_ (_stream_readable.js:737:12)
      at wrapped (node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
```

renderToString just throws the array away and renders `<script type="text/javascript"></script>`

**Comment by divmain** [comment]
Thanks for this.  If I have some free time this weekend, I'll pull branch off your PR and add the fix.
