### ISSUE TITLE
babel-plugin-server: prop without value

### ISSUE THREAD

**Issue by shuhei** [FormidableLabs/rapscallion#73]
`babel-plugin-server` throws an error on [a prop without value](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md).

A minimum test case:

```sh
$ echo '<Foo isFoo />;' | ./node_modules/.bin/babel --plugins ./src/transform/server
TypeError: unknown: Property value of ObjectProperty expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/Users/shuhei/work/js/rapscallion/node_modules/babel-types/lib/definitions/index.js:109:13)
    at validate (/Users/shuhei/work/js/rapscallion/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/Users/shuhei/work/js/rapscallion/node_modules/babel-types/lib/index.js:466:7)
    at attributes.map.attr (/Users/shuhei/work/js/rapscallion/src/transform/server.js:97:14)
    at Array.map (native)
    at getComponentProps (/Users/shuhei/work/js/rapscallion/src/transform/server.js:91:14)
    at prerenderComponent (/Users/shuhei/work/js/rapscallion/src/transform/server.js:67:31)
    at PluginPass.enter (/Users/shuhei/work/js/rapscallion/src/transform/server.js:21:13)
    at newFn (/Users/shuhei/work/js/rapscallion/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/shuhei/work/js/rapscallion/node_modules/babel-traverse/lib/path/context.js:76:18)
```

**Comment by ismay** [comment]
I've run into this as well: https://github.com/ismay/ismaywolff.nl/pull/406 (caused by this [property](https://github.com/ismay/ismaywolff.nl/blob/453516ebe5784e84716e88db2e39e37284feb14b/src/shared/components/images/components/Zoomable.jsx#L47))

**Comment by bkniffler** [comment]
Any news?

**Comment by ethersage** [comment]
Sorry I will try to look at this

**Comment by ethersage** [comment]
@bkniffler ☝️ Would you mind giving the above PR a review?

**Comment by ethersage** [comment]
@shuhei @ismay Would you mind giving the above PR a review please?

**Comment by ismay** [comment]
@ethersage Sorry I'm not familiar with this codebase and not using rapscallion at the moment, so I don't feel qualified to review this.
